### ISSUE TITLE
React Native Expo 51.0.4 Always failing with error -  Inconsistent JVM-target compatibility detected for tasks

### ISSUE THREAD

**Issue by neocafe** [livekit/client-sdk-react-native-expo-plugin#1] opened 2024-06-18 15:23 UTC
> Task :livekit-react-native-expo-plugin:compileDebugKotlin FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':livekit-react-native-expo-plugin:compileDebugKotlin'.
> Inconsistent JVM-target compatibility detected for tasks 'compileDebugJavaWithJavac' (17) and 'compileDebugKotlin' (21).

**Comment by BioJorge** [comment] 2024-07-04 01:52
having the same problem. Have no idea how to fix, please help.

**Comment by dmitryame** [comment] 2024-07-05 21:01
same here for me, please help!!!

**Comment by dmitryame** [comment] 2024-07-06 15:05
I solved my problem, one of my dependencies was out of date, I was able to figure it out from the error message in the build log. Once I updated the npm dependency to the latest version -- everything builds now.

**Comment by neocafe** [comment] 2024-07-06 17:53
@dmitryame Hi can you please let us know which dependency you changed

**Comment by erenkulaksiz** [comment] 2024-07-18 16:27
same here.

**Comment by dmitryame** [comment] 2024-07-18 16:41
It's hard to say for me, my logs are gone now, and I have updated so many dependencies in that PR. It's going to be specific for every case. Can you share more detailed log in this thread to help to understand your specific case?

**Comment by erenkulaksiz** [comment] 2024-07-22 09:31
Our package.json:
```
"@livekit/react-native": "^2.3.1",
"@livekit/react-native-expo-plugin": "^1.0.0",
"@livekit/react-native-webrtc": "^125.0.0",
```
When i try to build the app:

```
      │ > Task :livekit-react-native-expo-plugin:compileDebugKotlin FAILED
      │
      │ FAILURE: Build failed with an exception.
      │
      │ * What went wrong:
      │ Execution failed for task ':livekit-react-native-expo-plugin:compileDebugKotlin'.
      │ > Inconsistent JVM-target compatibility detected for tasks 'compileDebugJavaWithJavac'
      │ (17) and 'compileDebugKotlin' (20).
      │
      │   Consider using JVM Toolchain: https://kotl.in/gradle/jvm/toolchain
      │   Learn more about JVM-target validation: https://kotl.in/gradle/jvm/target-validation
      │
      │ * Try:
      │ > Run with --stacktrace option to get the stack trace.
      │ > Run with --info or --debug option to get more log output.
      │ > Run with --scan to get full insights.
      │ > Get more help at https://help.gradle.org.
      │
      │ Deprecated Gradle features were used in this build, making it incompatible with Gradle
      │ 9.0.
      │
      │ You can use '--warning-mode all' to show the individual deprecation warnings and determ
      │ ine if they come from your own scripts or plugins.
      │
      │ For more on this, please refer to https://docs.gradle.org/8.6/userguide/command_line_in
      │ terface.html#sec:command_line_warnings in the Gradle documentation.
      │
      │ BUİLD FAILED in 18s
      │ 602 actionable tasks: 124 executed, 466 from cache, 12 up-to-date
```

**Comment by erenkulaksiz** [comment] 2024-07-22 09:53
I've solved the issue by temporarily removing this package and adding this code to ./plugins/withLiveKit.js and adding it to app.json as a plugin.

```js

const { withAndroidManifest, AndroidConfig } = require('expo/config-plugins');

const withLiveKit = (config, options) => {
  if (options) {
    let androidOptions = options.android;
    if (androidOptions) {
      let audioType = androidOptions.audioType;
      if (audioType) {
        config = withAndroidManifest(config, (config) => {
          const mainApplication = AndroidConfig.Manifest.getMainApplicationOrThrow(
            config.modResults
          );

          AndroidConfig.Manifest.addMetaDataItemToMainApplication(
            mainApplication,
            'io.livekit.reactnative.expo.ANDROID_AUDIO_TYPE',
            audioType
          );
          return config;
        });
      }
    }
  }

  return config;
};

module.exports = withLiveKit;
```

**Comment by Cheizr** [comment] 2024-09-09 13:04
Fresh installation.

npx expo run:android


FAILURE: Build failed with an exception.

```
* What went wrong:
Execution failed for task ':react-native-can-draw-overlays:kaptGenerateStubsDebugKotlin'.
> Inconsistent JVM-target compatibility detected for tasks 'compileDebugJavaWithJavac' (17) and 'kaptGenerateStubsDebugKotlin' (1.8).
```

**Comment by Jonatthu** [comment] 2024-09-26 21:19
This is happening to me too

**Comment by boussaidev** [comment] 2024-10-01 09:39
### Fix for Java Version Compatibility Issue

I followed the steps below, and the issue is now fixed:

1. **Download JDK 17**:  
   Choose one of the following JDK 17 packages based on your system architecture:

   **For macOS:**
   | Product/File Description | File Size | Download |
   | ------------------------ | --------- | -------- |
   | ARM64 Compressed Archive | 168.84 MB | [Download](https://download.oracle.com/java/17/latest/jdk-17_macos-aarch64_bin.tar.gz) (sha256) |
   | ARM64 DMG Installer | 168.24 MB | [Download](https://download.oracle.com/java/17/latest/jdk-17_macos-aarch64_bin.dmg) (sha256) |
   | x64 Compressed Archive | 170.91 MB | [Download](https://download.oracle.com/java/17/latest/jdk-17_macos-x64_bin.tar.gz) (sha256) |
   | x64 DMG Installer | 170.32 MB | [Download](https://download.oracle.com/java/17/latest/jdk-17_macos-x64_bin.dmg) (sha256) |

   **For Linux:**
   | Product/File Description | File Size | Download |
   | ------------------------ | --------- | -------- |
   | ARM64 Compressed Archive | 172.92 MB | [Download](https://download.oracle.com/java/17/latest/jdk-17_linux-aarch64_bin.tar.gz) (sha256) |
   | ARM64 RPM Package | 172.62 MB | [Download](https://download.oracle.com/java/17/latest/jdk-17_linux-aarch64_bin.rpm) (sha256) |
   | x64 Compressed Archive | 174.33 MB | [Download](https://download.oracle.com/java/17/latest/jdk-17_linux-x64_bin.tar.gz) (sha256) |
   | x64 Debian Package | 149.69 MB | [Download](https://download.oracle.com/java/17/latest/jdk-17_linux-x64_bin.deb) (sha256) |
   | x64 RPM Package | 174.03 MB | [Download](https://download.oracle.com/java/17/latest/jdk-17_linux-x64_bin.rpm) (sha256) |

   **For Windows:**
   | Product/File Description | File Size | Download |
   | ------------------------ | --------- | -------- |
   | x64 Compressed Archive | 172.87 MB | [Download](https://download.oracle.com/java/17/latest/jdk-17_windows-x64_bin.zip) (sha256) |
   | x64 Installer | 153.92 MB | [Download](https://download.oracle.com/java/17/latest/jdk-17_windows-x64_bin.exe) (sha256) |
   | x64 MSI Installer | 152.67 MB | [Download](https://download.oracle.com/java/17/latest/jdk-17_windows-x64_bin.msi) (sha256) |

2. **Update JAVA_HOME**:  
   After downloading and installing JDK 17, update your `JAVA_HOME` variable in your `.bash_profile` by adding the following lines:

   ```bash
   export ANDROID_HOME=~/Library/Android/sdk
   export PATH=$PATH:$ANDROID_HOME/emulator
   export PATH=$PATH:$ANDROID_HOME/tools
   export PATH=$PATH:$ANDROID_HOME/tools/bin
   export PATH=$PATH:$ANDROID_HOME/platform-tools
   export JAVA_HOME=$(/usr/libexec/java_home -v 17)
   export PATH=$PATH:$JAVA_HOME/bin
   export NODE_OPTIONS=--openssl-legacy-provider
Make sure to run the following command to apply the changes immediately:

bash
Copy code
export JAVA_HOME=$(/usr/libexec/java_home -v 17)
Verify Installation:
You can verify that JDK 17 is correctly set up by running:

bash
Copy code
java -version
You should see output indicating that JDK 17 is in use.

**Comment by davidliu** [comment] 2024-10-04 04:11
Would anyone have a project reproing this issue? I haven't been able to repro this.

Also, Java 17 is highly recommended for Expo 50+ (not just for this plugin, but for Expo itself). You can follow the instructions given by @boussaidev, or Expo's instructions found [here](https://docs.expo.dev/workflow/android-studio-emulator/#install-dependencies). Android Studio also includes JDK 17, so you can use that as well (on Macs, usually found at `/Applications/Android Studio.app/Contents/jbr/Contents/Home`).

**Comment by Jonatthu** [comment] 2024-10-04 18:20
I was able to fix it when I deleted all java sdk's and only install one

**Closed** 2024-12-19 16:14 UTC
